CREATE TABLE [dbo].[Notice] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [NoticeDistributionID] INT            NULL,
    [SenderID]             INT            NULL,
    [ReceiverID]           INT            NOT NULL,
    [AddedDate]            DATETIME       NOT NULL,
    [ReadedDate]           DATETIME       NULL,
    [Caption]              NVARCHAR (500) NULL,
    [Text]                 NVARCHAR (MAX) NOT NULL,
    [Type]                 INT            NOT NULL,
    [ForumID]              INT            NULL,
    [MatchID]              INT            NULL,
    [TournamentID]         INT            NULL,
    [GameID]               INT            NULL,
    [GroupID]              INT            NULL,
    [SubjectID]            INT            NULL,
    [ChatRoomID]           INT            NULL,
    [IsCloseForRead]       BIT            NOT NULL,
    CONSTRAINT [PK_Notice] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Notice_ChatRoom] FOREIGN KEY ([ChatRoomID]) REFERENCES [dbo].[ChatRoom] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Notice_Forum] FOREIGN KEY ([ForumID]) REFERENCES [dbo].[Forum] ([ID]),
    CONSTRAINT [FK_Notice_Game] FOREIGN KEY ([GameID]) REFERENCES [dbo].[Game] ([ID]),
    CONSTRAINT [FK_Notice_Group] FOREIGN KEY ([GroupID]) REFERENCES [dbo].[Group] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Notice_Match] FOREIGN KEY ([MatchID]) REFERENCES [dbo].[Match] ([ID]),
    CONSTRAINT [FK_Notice_Notice] FOREIGN KEY ([ID]) REFERENCES [dbo].[Notice] ([ID]),
    CONSTRAINT [FK_Notice_NoticeDistirbution] FOREIGN KEY ([NoticeDistributionID]) REFERENCES [dbo].[NoticeDistribution] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Notice_Receiver] FOREIGN KEY ([ReceiverID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_Notice_Sender] FOREIGN KEY ([SenderID]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_Notice_Subject] FOREIGN KEY ([SubjectID]) REFERENCES [dbo].[Subject] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Notice_Tournament] FOREIGN KEY ([TournamentID]) REFERENCES [dbo].[Tournament] ([ID])
);

