CREATE TABLE [dbo].[Product] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [GameID]             INT            NULL,
    [Type]               INT            NOT NULL,
    [Name]               NVARCHAR (500) NOT NULL,
    [Url]                NVARCHAR (500) NOT NULL,
    [SubTitle]           NVARCHAR (500) NULL,
    [Image]              NVARCHAR (150) NULL,
    [Description]        NVARCHAR (MAX) NULL,
    [SmsName]            NVARCHAR (50)  NULL,
    [IsDeleted]          BIT            NOT NULL,
    [IsNew]              BIT            NOT NULL,
    [IsPromo]            BIT            NOT NULL,
    [IsAction]           BIT            NOT NULL,
    [VisitCount]         INT            NOT NULL,
    [VendorID]           INT            NULL,
    [CategoryID]         INT            NULL,
    [Background]         NVARCHAR (150) NULL,
    [ReleaseDate]        DATETIME       NULL,
    [SystemRequirements] NVARCHAR (MAX) NULL,
    [Creator]            NVARCHAR (100) NULL,
    [Publisher]          NVARCHAR (100) NULL,
    [RussianPublisher]   NVARCHAR (100) NULL,
    [Language]           NVARCHAR (500) NULL,
    [AgeRestrict]        INT            NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Product_Category] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[Category] ([ID]),
    CONSTRAINT [FK_Product_Game] FOREIGN KEY ([GameID]) REFERENCES [dbo].[Game] ([ID]) ON DELETE SET NULL ON UPDATE SET NULL,
    CONSTRAINT [FK_Product_Vendor] FOREIGN KEY ([VendorID]) REFERENCES [dbo].[Vendor] ([ID])
);

