CREATE TABLE [dbo].[Tournament] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [GameID]                INT            NOT NULL,
    [LeagueSeasonID]        INT            NULL,
    [LeagueLevelID]         INT            NULL,
    [TournamentType]        INT            NOT NULL,
    [PlayersCount]          INT            NULL,
    [MinLevel]              INT            NULL,
    [MaxLevel]              INT            NULL,
    [OpenRegistrationDate]  DATETIME       NOT NULL,
    [CloseRegistrationDate] DATETIME       NOT NULL,
    [BeginDate]             DATETIME       NOT NULL,
    [EndDate]               DATETIME       NOT NULL,
    [ImagePath]             NVARCHAR (150) NOT NULL,
    [Rules]                 NVARCHAR (MAX) NOT NULL,
    [CountRound]            INT            NOT NULL,
    [SingleWinPoint]        INT            NOT NULL,
    [SingleDrawPoint]       INT            NOT NULL,
    [Name]                  NVARCHAR (500) NOT NULL,
    [Url]                   NVARCHAR (500) NOT NULL,
    [PlatformID]            INT            NOT NULL,
    [Status]                INT            NOT NULL,
    [HostGuest]             BIT            NOT NULL,
    [DoubleGoalInGuest]     BIT            NOT NULL,
    [GroupCount]            INT            NOT NULL,
    [PlayersInGroup]        INT            NOT NULL,
    [ExitFromGroup]         INT            NOT NULL,
    [Toss]                  BIT            NOT NULL,
    [IsLive]                BIT            NOT NULL,
    [Place]                 NVARCHAR (500) NULL,
    [IsRoundForPoints]      BIT            NOT NULL,
    [ForumID]               INT            NULL,
    [TournamentConditionID] INT            NULL,
    [IsTeam]                BIT            NOT NULL,
    [TeamCount]             INT            NOT NULL,
    [Description]           NVARCHAR (MAX) NULL,
    [HotReplacement]        INT            NULL,
    [IsGroup]               BIT            NOT NULL,
    [Keywords]              NVARCHAR (MAX) NULL,
    [MetaDescription]       NVARCHAR (MAX) NULL,
    [MoneyType]             INT            NULL,
    [Fee]                   FLOAT (53)     NULL,
    CONSTRAINT [PK_Tournament] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Tournament_Forum] FOREIGN KEY ([ForumID]) REFERENCES [dbo].[Forum] ([ID]) ON DELETE SET NULL ON UPDATE SET NULL,
    CONSTRAINT [FK_Tournament_Game] FOREIGN KEY ([GameID]) REFERENCES [dbo].[Game] ([ID]),
    CONSTRAINT [FK_Tournament_LeagueLevel] FOREIGN KEY ([LeagueLevelID]) REFERENCES [dbo].[LeagueLevel] ([ID]),
    CONSTRAINT [FK_Tournament_LeagueSeason] FOREIGN KEY ([LeagueSeasonID]) REFERENCES [dbo].[LeagueSeason] ([ID]),
    CONSTRAINT [FK_Tournament_Platform] FOREIGN KEY ([PlatformID]) REFERENCES [dbo].[Platform] ([ID]),
    CONSTRAINT [FK_Tournament_TournamentCondition] FOREIGN KEY ([TournamentConditionID]) REFERENCES [dbo].[TournamentCondition] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

